Improve semantics
w3c/N3 pull request #194
Opened 2023-06-30 17:50 UTC by pchampin

long overdue review of the semantics document

2023-06-30 18:14 UTC, domel approved these changes

2023-06-30 18:37 UTC, TallTed requested changes

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
> +      has been interpreted contradictively by different reasoners in the past &ndash;  we decided to introduce an abstract syntax in which aspects like quantification
```suggestion
      to leave room for ambiguity &mdash; especially implicit quantification
      has been interpreted in contradicting ways by different reasoners in the past &mdash;  we decided to introduce an abstract syntax in which aspects like quantification 
```

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
> +   quantified variables. In case universals (i.e., variables starting with a question mark in the concrete syntax) are used, they stand for implicitly
```suggestion
   <p>Notation3 supports implicit quantification. When blank nodes are used in triples, they implicitly stand for existentially
   quantified variables. When universals (i.e., variables starting with a question mark in the concrete syntax) are used, they implicitly stand for
```

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
>     (e.g., if implicit existential quantification occurs in a graph term, it spans only that graph term).
```suggestion
   universally quantified variables. Implicit universal quantification is always global; that is, implicit universal quantification
   always spans over the full graph. Implicit existential quantification is always local; that is, it spans the local graph
   (i.e., if implicit existential quantification occurs in a graph term, it spans only that graph term).
```

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
> +  graph round brackets for all graph terms here and in the remainder of the document. That is, we will for example write<br/>
```suggestion
  graph parentheses ("<code>()</code>") for all graph terms here and in the remainder of the document. That is, for example, we will write<br/>
```

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
> +        More concrete, that means that the N3-turtle triple<br/>
```suggestion
        More concretely, that means that the N3-turtle triple<br/> 
```

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
> +              A graph term is a <a>direct constituent</a> of the graph ("containing graph") it occurs in as a triple component. However, the direct constituents of the graph term's graph, and their d
```suggestion
              A graph term is a <a>direct constituent</a> of the graph ("containing graph") in which it occurs as a triple component. However, the direct constituents of the graph term's graph, and their direct constituents (and so on), are not direct constituents of the containing graph. Rather, they are <a>constituents</a> of the containing graph.
```

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
>  scoping.
```suggestion
We would like to define our semantics in a way which assigns the <em>same
meaning for structurally identical graphs</em>, i.e., graphs which only
differ in the naming of the variables they use. To enable this, we first
introduce the concept of combined mappings which will be relevant to
handling nested graphs with local scoping.
```

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
> +      and <code>{_:x :p :o. _:y :p :o}</code> we thus get:</p>
```suggestion
      and <code>{_:x :p :o. _:y :p :o}</code>, we thus get:</p>
```

2023-06-30 18:37 UTC, TallTed commented on spec/semantics.html
>        However, as we will see below, N3 provides mechanisms to <a>unquote</a>  graph terms (that is, to transform them into graphs) and to compare them based on the meaning of the formula they quote.
```suggestion
      However, as we will see below, N3 provides mechanisms to <a>unquote</a>
      graph terms (that is, to transform them into graphs), and to compare them
      based on the meaning of the formulae they quote.
```

2023-07-01 13:53 UTC, william-vw commented on spec/semantics.html
> +            :loisLane :belives {:superman :can :fly}.
```suggestion
            :loisLane :believes {:superman :can :fly}.
```

2023-07-01 13:54 UTC, william-vw commented on spec/semantics.html
> +        which freely translates to <q>everyone says about themself that they are wise</q>.  In abstract syntax, the formula would be expressed as:
```suggestion
        which freely translates to <q>everyone says about themselves that they are wise</q>.  In abstract syntax, the formula would be expressed as:
```

2023-07-01 13:55 UTC, william-vw commented on spec/semantics.html
>            Note that the interpretation function $Q_I(x)$ maps ground graphs into the domain of discourse without interpreting their content seperately.
```suggestion
          Note that the interpretation function $Q_I(x)$ maps ground graphs into the domain of discourse without interpreting their content separately. 
```

2023-07-01 13:59 UTC, william-vw commented on spec/semantics.html
> +We would like to define our semantics in a way which assigns the <em>same meaning for structurally identical graphs</em>, i.e., graph which only differ in the naming of the variables they use. To be
```suggestion
We would like to define our semantics in a way which assigns the <em>same meaning for structurally identical graphs</em>, i.e., graphs which only differ in the naming of the variables they use. To be able to do so, we first introduce the concept of combined mappings which will be relevant to handle nested graphs with local 
```

2023-07-01 14:06 UTC, william-vw requested changes
See suggestions

2023-07-01 14:13 UTC, william-vw approved these changes

2023-07-01 14:14 UTC, william-vw requested changes
See suggestions

2023-07-01 14:17 UTC, william-vw approved these changes

2023-07-01 14:21 UTC, merged